from typing import Union, Awaitable, Any, Callable, Optional, Dict, List

class Api:
    def call_action(self , action: str, **params) -> Union[Awaitable[Any], Any]:...

    def SendTextMsg(self, to_wxid : str, msg : str):...

    def SendImageMsg(self, to_wxid : str, msg : str):...

    def SendVideoMsg(self, to_wxid : str, msg : str):...

    def SendFileMsg(self, to_wxid : str, msg : str):...

    def GetRobotName(self) -> str:...

    def GetFriendList(self) -> List[Dict[str, Any]]:...

    def GetGroupList(self) -> List[Dict[str, Any]]:...

    def GetGroupMemberList(self, group_wxid : str) -> List[Dict[str, Any]]:...

    def GetGroupMemberInfo(self, group_wxid : str, member_wxid : str) -> Dict[str, Any]:...

    def AcceptTransfer(self, to_wxid : str, msg : str):...

    def AgreeGroupInvite(self, msg : str):...

    def AgreeeFriendVerify(self, msg : str):...

    def GetAppDir(self) -> str:...